<?php

return [
    'pages' => [
        'home' => [
            'label' => 'Trang chủ',
            'fields' => [
                'hero_subtitle' => ['label' => 'Hero - dòng nhỏ', 'type' => 'text', 'default' => 'Chào Mừng'],
                'hero_title' => ['label' => 'Hero - tiêu đề', 'type' => 'text', 'default' => 'Tạo danh sách mong muốn của bạn'],
                'hero_description' => ['label' => 'Hero - mô tả', 'type' => 'textarea', 'default' => 'Hãy tạo danh sách của riêng bạn cho các dịp trọng đại (Sinh nhật, Giáng sinh, Lễ Tết). Thêm mặt hàng từ cửa hàng bất kỳ và chia sẻ với mọi người bạn yêu quý.'],
                'hero_button' => ['label' => 'Hero - nút', 'type' => 'text', 'default' => 'KHÁM PHÁ NGAY'],
                'hero_slide_1' => ['label' => 'Hero slider ảnh 1', 'type' => 'image', 'default' => ''],
                'hero_slide_2' => ['label' => 'Hero slider ảnh 2', 'type' => 'image', 'default' => ''],
                'hero_slide_3' => ['label' => 'Hero slider ảnh 3', 'type' => 'image', 'default' => ''],
                'tabs_slide_1' => ['label' => 'Tabs slider ảnh 1', 'type' => 'image', 'default' => ''],
                'tabs_slide_2' => ['label' => 'Tabs slider ảnh 2', 'type' => 'image', 'default' => ''],
                'tabs_slide_3' => ['label' => 'Tabs slider ảnh 3', 'type' => 'image', 'default' => ''],
                'tabs_slide_4' => ['label' => 'Tabs slider ảnh 4', 'type' => 'image', 'default' => ''],
                'stats_image' => ['label' => 'Ảnh phần Thống kê', 'type' => 'image', 'default' => ''],
                'blog_post_image_1' => ['label' => 'Blog bài 1 ảnh', 'type' => 'image', 'default' => ''],
                'blog_post_image_2' => ['label' => 'Blog bài 2 ảnh', 'type' => 'image', 'default' => ''],
                'blog_post_image_3' => ['label' => 'Blog bài 3 ảnh', 'type' => 'image', 'default' => ''],
                'blog_author_image_1' => ['label' => 'Blog tác giả 1 ảnh', 'type' => 'image', 'default' => ''],
                'blog_author_image_2' => ['label' => 'Blog tác giả 2 ảnh', 'type' => 'image', 'default' => ''],
                'blog_author_image_3' => ['label' => 'Blog tác giả 3 ảnh', 'type' => 'image', 'default' => ''],
                'testimonial_image_1' => ['label' => 'Testimonial ảnh 1', 'type' => 'image', 'default' => ''],
                'testimonial_image_2' => ['label' => 'Testimonial ảnh 2', 'type' => 'image', 'default' => ''],
                'testimonial_image_3' => ['label' => 'Testimonial ảnh 3', 'type' => 'image', 'default' => ''],
                'stats_subtitle' => ['label' => 'Thống kê - dòng nhỏ', 'type' => 'text', 'default' => 'Thống Kê'],
                'stats_title' => ['label' => 'Thống kê - tiêu đề', 'type' => 'text', 'default' => 'Sự Hài Lòng Của Khách Hàng'],
                'stats_description' => ['label' => 'Thống kê - mô tả', 'type' => 'textarea', 'default' => 'Sự hài lòng của khách hàng là ưu tiên hàng đầu của chúng tôi. Chúng tôi cam kết cung cấp dịch vụ chất lượng và sản phẩm tốt nhất để đáp ứng nhu cầu của bạn.'],
                'services_subtitle' => ['label' => 'Dịch vụ - dòng nhỏ', 'type' => 'text', 'default' => 'Dịch vụ'],
                'services_title' => ['label' => 'Dịch vụ - tiêu đề', 'type' => 'text', 'default' => 'Công cụ gợi ý quà tặng cho mọi dịp'],
                'services_description' => ['label' => 'Dịch vụ - mô tả', 'type' => 'textarea', 'default' => 'Lưu ý tưởng, so sánh sản phẩm, theo dõi giá và chia sẻ danh sách yêu thích với người thân một cách dễ dàng.'],
                'services_button' => ['label' => 'Dịch vụ - nút', 'type' => 'text', 'default' => 'Bắt đầu'],
                'blog_kicker' => ['label' => 'Bài viết - dòng nhỏ', 'type' => 'text', 'default' => 'Gợi Ý Sản Phẩm'],
                'blog_title' => ['label' => 'Bài viết - tiêu đề', 'type' => 'text', 'default' => 'Những Bài Viết Mới Nhất'],
                'faq_kicker' => ['label' => 'FAQ - dòng nhỏ', 'type' => 'text', 'default' => 'Hỏi đáp'],
                'faq_title' => ['label' => 'FAQ - tiêu đề', 'type' => 'text', 'default' => 'Câu Hỏi Thường Gặp'],
                'testimonials_title' => ['label' => 'Đánh giá - tiêu đề', 'type' => 'text', 'default' => 'TRẢI NGHIỆM NGƯỜI DÙNG TẠI AGIFT'],
            ],
        ],
        'blog' => [
            'label' => 'Bài viết',
            'fields' => [
                'nav_all' => ['label' => 'Tab tất cả', 'type' => 'text', 'default' => 'Tất cả'],
                'empty_message' => ['label' => 'Thông báo khi trống', 'type' => 'text', 'default' => 'Hiện chưa có bài viết cho danh mục này.'],
                'featured_badge' => ['label' => 'Nhãn bài nổi bật', 'type' => 'text', 'default' => 'Gợi ý nổi bật'],
                'categories_title' => ['label' => 'Tiêu đề danh mục', 'type' => 'text', 'default' => 'Khám phá theo danh mục'],
                'products_title' => ['label' => 'Tiêu đề gợi ý', 'type' => 'text', 'default' => 'Gợi ý thêm cho bạn'],
            ],
        ],
        'about' => [
            'label' => 'Giới thiệu',
            'fields' => [
                'page_title' => ['label' => 'Tiêu đề trang', 'type' => 'text', 'default' => 'About'],
                'breadcrumb_home' => ['label' => 'Breadcrumb trang chủ', 'type' => 'text', 'default' => 'Home'],
                'mission_subtitle' => ['label' => 'Sứ mệnh - dòng nhỏ', 'type' => 'text', 'default' => 'Our Mission'],
                'mission_title' => ['label' => 'Sứ mệnh - tiêu đề', 'type' => 'textarea', 'default' => 'The Big Oxmox advised her not to do so, because there were thousands.'],
                'mission_lead' => ['label' => 'Sứ mệnh - mô tả 1', 'type' => 'textarea', 'default' => 'A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country.'],
                'mission_body' => ['label' => 'Sứ mệnh - mô tả 2', 'type' => 'textarea', 'default' => 'The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli.'],
                'mission_button' => ['label' => 'Sứ mệnh - nút', 'type' => 'text', 'default' => 'Get Started'],
                'why_subtitle' => ['label' => 'Vì sao - dòng nhỏ', 'type' => 'text', 'default' => 'Why Us'],
                'why_title' => ['label' => 'Vì sao - tiêu đề', 'type' => 'text', 'default' => 'Far far away Behind the Word Mountains'],
                'why_lead' => ['label' => 'Vì sao - mô tả 1', 'type' => 'textarea', 'default' => 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.'],
                'why_body' => ['label' => 'Vì sao - mô tả 2', 'type' => 'textarea', 'default' => 'There live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.'],
            ],
        ],
        'team' => [
            'label' => 'Cảm hứng',
            'fields' => [
                'page_title' => ['label' => 'Tiêu đề trang', 'type' => 'text', 'default' => 'Cảm hứng quà tặng'],
                'page_description' => ['label' => 'Mô tả trang', 'type' => 'textarea', 'default' => 'Khám phá những sản phẩm phù hợp cho từng người nhận và từng dịp đặc biệt.'],
                'filter_all' => ['label' => 'Bộ lọc tất cả', 'type' => 'text', 'default' => 'Tất cả'],
            ],
        ],
        'occasions' => [
            'label' => 'Dịp trong năm',
            'fields' => [
                'page_title' => ['label' => 'Tiêu đề trang', 'type' => 'text', 'default' => 'Khám phá dịp trong năm'],
                'page_description' => ['label' => 'Mô tả trang', 'type' => 'textarea', 'default' => 'Chọn danh mục và dịp phù hợp để tìm bài viết và gợi ý sản phẩm cho mọi khoảnh khắc.'],
                'filter_all' => ['label' => 'Nhãn bộ lọc tất cả', 'type' => 'text', 'default' => 'Tất cả dịp'],
                'articles_section_title' => ['label' => 'Tiêu đề phần bài viết', 'type' => 'text', 'default' => 'Bài viết phù hợp dịp'],
                'products_section_title' => ['label' => 'Tiêu đề phần gợi ý sản phẩm', 'type' => 'text', 'default' => 'Gợi ý sản phẩm'],
                'products_section_description' => ['label' => 'Mô tả phần gợi ý sản phẩm', 'type' => 'textarea', 'default' => 'Sản phẩm phù hợp với dịp và danh mục bạn đang tìm.'],
                'categories_section_title' => ['label' => 'Tiêu đề phần danh mục', 'type' => 'text', 'default' => 'Danh mục bài viết'],
            ],
        ],
        'portfolio' => [
            'label' => 'Hoạt động',
            'fields' => [
                'title' => ['label' => 'Tiêu đề', 'type' => 'text', 'default' => 'Trang Portfolio'],
                'description' => ['label' => 'Mô tả', 'type' => 'textarea', 'default' => 'Đây là trang Portfolio. Nội dung sẽ được cập nhật sau.'],
            ],
        ],
        'article' => [
            'label' => 'Chi tiết bài viết',
            'fields' => [
                'related_title' => ['label' => 'Tiêu đề bài liên quan', 'type' => 'text', 'default' => 'Bài viết liên quan'],
                'back_to_blog' => ['label' => 'Nút quay lại', 'type' => 'text', 'default' => 'Quay lại Blog'],
            ],
        ],
        'profile' => [
            'label' => 'Danh sách mong muốn',
            'fields' => [
                'title' => ['label' => 'Tiêu đề', 'type' => 'text', 'default' => 'Danh sách mong muốn'],
                'empty_message' => ['label' => 'Thông báo khi trống', 'type' => 'textarea', 'default' => 'Chưa có sản phẩm nào trong danh sách.'],
            ],
        ],
        'search' => [
            'label' => 'Tìm kiếm',
            'fields' => [
                'title' => ['label' => 'Tiêu đề tìm kiếm', 'type' => 'text', 'default' => 'Kết quả tìm kiếm'],
                'empty_message' => ['label' => 'Thông báo không có kết quả', 'type' => 'textarea', 'default' => 'Không tìm thấy nội dung phù hợp.'],
            ],
        ],
        'site' => [
            'label' => 'Nội dung chung',
            'fields' => [
                'site_logo' => ['label' => 'Logo trang (ảnh)', 'type' => 'image', 'default' => ''],
                'nav_home' => ['label' => 'Nav - Trang Chủ', 'type' => 'text', 'default' => 'Trang Chủ'],
                'nav_services' => ['label' => 'Nav - Danh Sách Mong Muốn', 'type' => 'text', 'default' => 'Danh Sách Mong Muốn'],
                'nav_team' => ['label' => 'Nav - Cảm Hứng', 'type' => 'text', 'default' => 'Cảm Hứng'],
                'nav_blog' => ['label' => 'Nav - Bài Viết', 'type' => 'text', 'default' => 'Bài Viết'],
                'nav_occasions' => ['label' => 'Nav - Dịp Trong Năm', 'type' => 'text', 'default' => 'Dịp Trong Năm'],
                'nav_portfolio' => ['label' => 'Nav - Hoạt Động', 'type' => 'text', 'default' => 'Hoạt Động'],
                'footer_about_title' => ['label' => 'Footer - Tiêu đề giới thiệu', 'type' => 'text', 'default' => 'AGIFT'],
                'footer_about_description' => ['label' => 'Footer - Mô tả giới thiệu', 'type' => 'textarea', 'default' => 'Khám phá những sản phẩm yêu thích, tạo danh sách cho cuộc sống của riêng bạn và chia sẻ với mọi người. Công cụ hoàn toàn miễn phí cho mọi dịp.'],
                'footer_cta_text' => ['label' => 'Footer - nút/văn bản CTA', 'type' => 'text', 'default' => 'Khám phá ngay >'],
                'footer_links_title' => ['label' => 'Footer - Tiêu đề liên kết', 'type' => 'text', 'default' => 'Tổng quan'],
                'footer_link_1_label' => ['label' => 'Footer link 1 - nhãn', 'type' => 'text', 'default' => 'Blog'],
                'footer_link_1_url' => ['label' => 'Footer link 1 - url', 'type' => 'text', 'default' => '/blog'],
                'footer_link_2_label' => ['label' => 'Footer link 2 - nhãn', 'type' => 'text', 'default' => 'Cách thức hoạt động'],
                'footer_link_2_url' => ['label' => 'Footer link 2 - url', 'type' => 'text', 'default' => '#'],
                'footer_link_3_label' => ['label' => 'Footer link 3 - nhãn', 'type' => 'text', 'default' => 'Chính sách bảo mật'],
                'footer_link_3_url' => ['label' => 'Footer link 3 - url', 'type' => 'text', 'default' => '#'],
                'footer_link_4_label' => ['label' => 'Footer link 4 - nhãn', 'type' => 'text', 'default' => 'Điều khoản dịch vụ'],
                'footer_link_4_url' => ['label' => 'Footer link 4 - url', 'type' => 'text', 'default' => '#'],
                'footer_link_5_label' => ['label' => 'Footer link 5 - nhãn', 'type' => 'text', 'default' => 'Trung tâm trợ giúp'],
                'footer_link_5_url' => ['label' => 'Footer link 5 - url', 'type' => 'text', 'default' => '#'],
                'footer_contact_title' => ['label' => 'Footer - tiêu đề liên hệ', 'type' => 'text', 'default' => 'Liên hệ'],
                'footer_contact_phone' => ['label' => 'Footer - số điện thoại', 'type' => 'text', 'default' => '0900 000 000'],
                'footer_contact_email' => ['label' => 'Footer - email liên hệ', 'type' => 'text', 'default' => 'hello@agift.com'],
                'footer_contact_address' => ['label' => 'Footer - địa chỉ', 'type' => 'textarea', 'default' => '123 Đường ABC, Quận XYZ, TP.HCM'],
                'footer_support_title' => ['label' => 'Footer - tiêu đề hỗ trợ', 'type' => 'text', 'default' => 'Hỗ trợ khách hàng'],
                'footer_support_link_1_label' => ['label' => 'Footer hỗ trợ link 1 - nhãn', 'type' => 'text', 'default' => 'Trung tâm trợ giúp'],
                'footer_support_link_1_url' => ['label' => 'Footer hỗ trợ link 1 - url', 'type' => 'text', 'default' => '#'],
                'footer_support_link_2_label' => ['label' => 'Footer hỗ trợ link 2 - nhãn', 'type' => 'text', 'default' => 'Câu hỏi thường gặp'],
                'footer_support_link_2_url' => ['label' => 'Footer hỗ trợ link 2 - url', 'type' => 'text', 'default' => '#'],
                'footer_support_link_3_label' => ['label' => 'Footer hỗ trợ link 3 - nhãn', 'type' => 'text', 'default' => 'Chính sách đổi trả'],
                'footer_support_link_3_url' => ['label' => 'Footer hỗ trợ link 3 - url', 'type' => 'text', 'default' => '#'],
            ],
        ],
    ],
];
